# Author: Pedro Henrique Ribeiro Santiago
# Description: Creates a plot for Observed Scores vs DIF Adjusted Scores

###Loading required libraries###

install.packages("ggplot2")  #Install ggplot2 package
library(ggplot2) #Load ggplot2 package

#######################################################
### Observed Score x Adjusted DIF score - Design 1  ###
#######################################################

difobsadj = file.choose() #Choose the file generated by DIGRAM PersonLocations-comma.txt
difdata <- read.table(difobsadj, header = TRUE, sep = "", dec = ",") #Inputs the data into dataframe

#Creates the plot
ObsAdj <- ggplot(subset(difdata, difdata$P==2&difdata$R==2&difdata$T==2), aes(x=score)) + #Manually select the subgroup
  geom_bar(data=subset(difdata, difdata$P==2&difdata$R==2&difdata$T==2), 
           aes(x=score, weight=count), colour="orange", fill="orange", width=0.1, alpha=0.5) + #Modify color/transparency/width of obs scores
  geom_bar(data=subset(difdata, difdata$P==2&difdata$R==2&difdata$T==2), 
           aes(x=Escore, weight=count), colour="blue", fill="blue", width=0.1, alpha=0.5) + #Modify color/transparency/width of equated scores
  scale_x_continuous(breaks = round(seq(min(0), max(difdata$score), by = 1.0),1)) +
  theme_light() +
  labs(x = "DIF Adjusted Scores", y="Frequency of responses") + #Axis labels
  annotate("text", x = (max(difdata$score)-max((difdata$score/5))), 
           y = max(difdata$count[difdata$P==2&difdata$R==2&difdata$T==2])-max((difdata$count[difdata$P==2&difdata$R==2&difdata$T==2])/10), 
           label = print(paste0("Mean Observed Score = ", format(round(weighted.mean(difdata$score[difdata$P==2&difdata$R==2&difdata$T==2], 
                                                                                   difdata$count[difdata$P==2&difdata$R==2&difdata$T==2]), digits=2),
                                                                 nsmall=2)))) + #Annotates the Mean Observed Score
  annotate("text", x = (max(difdata$score)-max((difdata$score/5))), 
           y = max(difdata$count[difdata$P==2&difdata$R==2&difdata$T==2])-max((difdata$count[difdata$P==2&difdata$R==2&difdata$T==2])/5), 
           label = print(paste0("Mean Equated Score = ", format(round(weighted.mean(difdata$Escore[difdata$P==2&difdata$R==2&difdata$T==2], 
                                             difdata$count[difdata$P==2&difdata$R==2&difdata$T==2]), digits=2), nsmall=2)))) +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.minor = element_blank()) + #Annotates the Mean Equated Score
  ggtitle("Observed x Equated Scores") #Plot title

#Displays the plot
ObsAdj

#######################################################
### Observed Score x Adjusted DIF score - Design 2  ###
#######################################################

difobsadj2 = file.choose() #Choose the PersonLocation-comma.txt
difdata <- read.table(difobsadj2, header = TRUE, sep = "", dec = ",") #Inputs the data into dataframe 

ObsAdj2 <- ggplot(subset(difdata, difdata$S==2&difdata$R==2&difdata$T==2), aes(x=score)) + #Manually select the subgroup
  geom_line(data=subset(difdata, difdata$S==2&difdata$R==2&difdata$T==2), 
           aes(x=score, y=count), colour="orange", show.legend=TRUE) + #Modify color of obs scores
  geom_line(data=subset(difdata, difdata$S==2&difdata$R==2&difdata$T==2), 
           aes(x=Escore, y=count), colour="blue",  alpha=0.5, show.legend=TRUE) + #Modify color/transparency of equated scores
  geom_point(data=subset(difdata, difdata$S==2&difdata$R==2&difdata$T==2), 
            aes(x=score, y=count), colour="orange") + #Modify color of obs scores
  geom_point(data=subset(difdata, difdata$S==2&difdata$R==2&difdata$T==2), 
            aes(x=Escore, y=count), colour="blue",  alpha=0.5) + #Modify color/transparency of equated scores
  scale_x_continuous(breaks = round(seq(min(0), max(difdata$score), by = 1.0),1)) +
  theme_light() +
  labs(x = "Scores", y="Frequency of responses") + #Axis labels
  annotate("text", x = (max(difdata$score)-max((difdata$score/5))), 
           y = max(difdata$count[difdata$S==2&difdata$R==2&difdata$T==2])-max((difdata$count[difdata$S==2&difdata$R==2&difdata$T==2])/10), 
           label = print(paste0("Mean Observed Score = ", format(round(weighted.mean(difdata$score[difdata$S==2&difdata$R==2&difdata$T==2], 
                                                                              difdata$count[difdata$S==2&difdata$R==2&difdata$T==2]),
                                                                       digits=2), nsmall=2)))) + #Annotates the Mean Observed Score
  annotate("text", x = (max(difdata$score)-max((difdata$score/5))), 
           y = max(difdata$count[difdata$S==2&difdata$R==2&difdata$T==2])-max((difdata$count[difdata$S==2&difdata$R==2&difdata$T==2])/5), 
           label = print(paste0("Mean Equated Score = ", format(round(weighted.mean(difdata$Escore[difdata$S==2&difdata$R==2&difdata$T==2], 
                                                                             difdata$count[difdata$S==2&difdata$R==2&difdata$T==2]),
                                                                      digits=2), nsmall=2)))) + #Annotates the Mean Equated Score
  theme(plot.title = element_text(hjust = 0.5), panel.grid.minor = element_blank()) +
  ggtitle("Observed x Equated Scores") #Plot title

#Displays the plot
ObsAdj2
